import { formToJSON } from "axios";

export { default as About } from "./About";
export { default as Blog } from "./Blog";
// export { default as BlogPage} from "./BlogPage";
export { default as ChangePassword } from "./ChangePassword";
export { default as Contact } from "./ContactUs";
export { default as CreateStory } from "./CreateStory";
export { default as Dashboard } from "./Admin/UserDetails";
export { default as Error } from "./Error";
export { default as FAQ } from "./FAQ";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as Home } from "./Home";
export { default as HowToUse } from "./HowToUse";
export { default as Login } from "./Login";
export { default as MyStories } from "./MyStories";
export { default as Story } from "./Story";
export { default as Pricing } from "./Pricing";
export { default as Billing } from "./Billing";
export { default as CancelSubscription } from "./CancelSubscription";
export { default as Privacy } from "./Privacy";
export { default as Profile } from "./Profile";
export { default as ProfileEdit } from "./Profile/ProfileEdit";
export { default as SignUp } from "./SignUp";
export { default as SummaryActivities } from "./Users/SummaryActivities";
export { default as Info } from "./Users/Info";
export { default as Settings } from "./Settings";
export { default as Users } from "./Users/Users";
export {default as UserList} from "./Admin/UserList";
export {default as AdminLogin} from "./Admin/AdminLogin";
export {default as AdminSignup} from "./Admin/AdminLogin";
export {default as UserDetails} from "./Admin/UserDetails";
export { default as UserDashboard } from "./UserDashboard"
export { default as Archive } from "./Admin/Archive";
