export { default as About } from "./About";
export { default as Blog } from "./Blog";
export { default as BlogDetails } from "./BlogDetails";
export { default as ChangePassword } from "./ChangePassword";
export {default as Contact} from "./ContactUs"
export { default as CreateStory } from "./CreateStory";
export { default as Dashboard } from "./DashBoard";
export { default as Error } from "./Error";
export { default as FAQ } from "./FAQ";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as Home } from "./Home";
export { default as HowToUse } from "./HowToUse";
export { default as Login } from "./Login";
export { default as MyStories } from "./MyStories";
export { default as Pricing } from "./Pricing";
export { default as Privacy } from "./Privacy";
export { default as Profile } from "./Profile";
export { default as SignUp } from "./SignUp";
export { default as SummaryActivities } from "./SummaryActivities";
